### PR TITLE
Some bugs fixed.

### PR DESCRIPTION
**Pull request by aaronweihe**
Use `LegacyBar` instead of `ActionBar` in `FragmentTabActivity`.https://github.com/aaronmix/MonoDroid.ActionBar/commit/1a6e1680674cf77e68133fec0b2eee54d068fe24

Add the missing `MenuId` in `HomeActivity`. https://github.com/aaronmix/MonoDroid.ActionBar/commit/a3005ff3497e6f5d37c5954a56f9636eaac9ff6f This will cause exception when the user clicks the physical menu button. My device is Motoroal Droid. It runs Android 4.0 but still has physical menu button.

### CODE REVIEW

**Comment by Cheesebaron** [comment]
About the MenuId, do you mean adding it will make the phone crash when clicking the menu button, or when it is not present it crashes?

**Comment by aaronweihe** [comment]
If `MenuId` has not been assigned a value, it will make the phone crash when clicking the physical menu button.

**Comment by Cheesebaron** [comment]
Ah OK. Well it makes sense, since it expects `OnOptionsItemSelected` to be overriden.

**Comment by aaronweihe** [comment]
The change is on line 63:
`MenuId = Resource.Menu.mainmenu;`

**Comment by Cheesebaron** [comment]
I saw that :) Merged your changes. However for some reason github's diff tool was confused by your change and though the whole thing was changed, even though only one line was changed.

**Pull request merged**
